public class AccountCaseMap {
   // public static Map<Id, Case> fetchOpenCases(ID accId){
         Map<Id, Case> caseMapList = new Map<Id, Case>();
        //caseMapList.put(accId, case1);
     //  Case case1= new Case(Status='Working',Origin='Phone');
        /* Case case2= new Case(Status='New',Origin='Phone', AccountId=accId);
        Case case3= new Case(Status='New',Origin='Web', AccountId=accId);
        caseList.add(case1);
        caseList.add(case2);
        caseList.add(case3);
        system.debug(caseList);
        insert caseList;
        List<Case> caseList2 = new List<Case>();
        for(Case caseRec :caseList ){
        if(caseRec.Status=='New'){
           caseList2.add(caseRec);
        }
        }
        system.debug(caseList2);
        return caseList2;*/
   // }
}